#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [ -f ~/.zshrc.local ]; then
    . ~/.zshrc.local
fi

bindkey -v
bindkey -M vicmd v edit-command-line

if [[ $(hostname) == "Val-Kharitonov-MacBook-Pro" ]]; then
    test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

    [ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

    eval "$(register-python-argcomplete -e /Users/valkharitonov/bin/git_pr_complete.py --no-defaults git-pr)"
    
    #compdef gt
    ###-begin-gt-completions-###
    #
    # yargs command completion script
    #
    # Installation: /usr/local/bin/gt completion >> ~/.zshrc
    #    or /usr/local/bin/gt completion >> ~/.zprofile on OSX.
    #
    _gt_yargs_completions()
    {
      local reply
      local si=$IFS
      IFS=$'
    ' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" /usr/local/bin/gt --get-yargs-completions "${words[@]}"))
      IFS=$si
      _describe 'values' reply
    }
    compdef _gt_yargs_completions gt
    ###-end-gt-completions-###
fi

